### ISSUE TITLE
启动后下载数一直为0，但实际有文件写入

### ISSUE THREAD

**Issue by xxKawa** [justype/LoftTagDownloader#1]
`开始下载        0       0`

Log:
`【开始下载】requestPosition= 0, requestTime= 0`

**Comment by Justype** [comment]
下载要时间，只有重新请求的时候才会写日志，等一会就可以了。

下载文件的时候，可能会报 ReadTimeout 我正在改，等会

**Comment by Justype** [comment]
https://github.com/justype/LoftTagDownloader/commit/7f0506fd03221b309410235d38d5f2cf08a79594
已经捕获了 ReadTimeout 和 ConnectionError

**Comment by Justype** [comment]
好吧，又有问题，不能直接打印 ReadTimeout 和 ConnectionError
https://github.com/justype/LoftTagDownloader/commit/48dc0e90aa69e0bb507b13b831c084091c1dfcc6
去掉了log 错误信息

**Comment by Justype** [comment]
![image](https://user-images.githubusercontent.com/45914566/84561297-d1c3aa80-ad7d-11ea-9e18-818ecc677dec.png)
https://github.com/justype/LoftTagDownloader/commit/d7f019d53df926137ff38834c69a1911ed2c43ad
已经能够输出详细信息了
